//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVmvc.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCvEntities : DbContext
    {
        public DbCvEntities()
            : base("name=DbCvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ABILITY> TBL_ABILITY { get; set; }
        public virtual DbSet<TBL_ABOUT> TBL_ABOUT { get; set; }
        public virtual DbSet<TBL_ADMIN> TBL_ADMIN { get; set; }
        public virtual DbSet<TBL_CONNECT> TBL_CONNECT { get; set; }
        public virtual DbSet<TBL_EDUCATION> TBL_EDUCATION { get; set; }
        public virtual DbSet<TBL_EXPERIANCE> TBL_EXPERIANCE { get; set; }
        public virtual DbSet<TBL_HOBILERIM> TBL_HOBILERIM { get; set; }
        public virtual DbSet<TBL_SERTIFIKA> TBL_SERTIFIKA { get; set; }
    }
}
