//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVmvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CONNECT
    {
        public int ID { get; set; }
        public string NAMESURNAME { get; set; }
        public string MAIL { get; set; }
        public string SUBJECT { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    }
}
