//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVmvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_EDUCATION
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Bu Alani Bos Gecemezsiniz")]
        public string HEADING { get; set; }
        public string HEADINGBELOW { get; set; }
        public string HEADINGBELOW2 { get; set; }
        public string GNO { get; set; }
        public string DATE { get; set; }
    }
}
