//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVmvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ABOUT
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string MAIL { get; set; }
        public string EXPLANATION { get; set; }
        public string PHOTO { get; set; }
    }
}
